version: '3'

services:
  # Database for the api
  postgres:
    image: postgres:14.1
    volumes:
      - ./res/docker_mounts/:/var/lib/postgres/data
      - ./res/data.sql/:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  # The api, includes the API and Client
  api:
    image: ecommerce-demo:1.0
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    env_file: .env
    environment:
        DB_HOST: postgres
        DB_PORT: 5432
        DB_PASS: postgres
        DATABASE: bookstore
    ports:
      - "3000:3000"
    depends_on:
      - postgres
